### ISSUE TITLE
Adpot the configuration structure

### ISSUE THREAD

**Issue by tamdaz** [tamdaz/cruml#41]
## Description

At present, it is not possible to automatically group classes. The solution is to adopt a `.yml` configuration file with the following structure.

```yml
colors:
  light:
    classes: <Hexadecimal color>
    abstract_classes: <Hexadecimal color>
    interfaces: <Hexadecimal color>
    modules: <Hexadecimal color>
  dark:
    classes: <Hexadecimal color>
    abstract_classes: <Hexadecimal color>
    interfaces: <Hexadecimal color>
    modules: <Hexadecimal color>

namespaces:
  <Namespace>:
    - <A list of classes>
```

In addition, we can add another part of this configuration dedicated to object type colors.
Namespaces can be created as many times as we want to better group some classes.

## Example

```yml
colors:
  light:
    classes: "#baa7e5"
    abstract_classes: "#a7e5a7"
    interfaces: "#e2c7a3"
    modules: "#5ab3f4"
  dark:
    classes: "#baa7e5"
    abstract_classes: "#a7e5a7"
    interfaces: "#e2c7a3"
    modules: "#5ab3f4"

namespaces:
  E8:
    - E8::ObjectInterface
    - E8::AbstractShape
    - E8::Circle
    - E8::Rectangle
    - E8::Triangle
```
